#!/usr/bin/env python3
"""Emit a fast address -> native function index for one generated module.

DolRecomp's generated.h resolves a guest address to its function with
`dolrecomp_find_original`: a chain of range tests, one per block of
functions. The C backend emits a few hundred large chunks, so the chain is
short. The LLVM backend emits one region per function - 21,594 for the
engine - and the chain becomes some 13,000 tests walked on every dispatch:
62% of a profile of the intro movie, at 0.5 fps (HANDOFF F362).

This reads the same chain out of generated.h and writes it as sorted data,
so the bridge can binary-search it. Both forms the header uses are read:

    stride blocks   u32 offset = address - START;
                    if (offset < SIZE && (offset & 3u) == 0u) {
                        static const DolRecompFunction chunk_functions[] = { f, ... };
                        return chunk_functions[offset / STRIDE];
                    }
    single ranges   if (address >= A && address < B && ((address - A) & 3u) == 0u)
                        return func_X;

The mapping is copied, not re-derived: an address resolves to exactly the
function the header's own lookup would return.

usage: gen_native_index.py <generated-dir> <prefix> <out.inc>
"""
import re
import sys
from pathlib import Path

gen, prefix, out = Path(sys.argv[1]), sys.argv[2], Path(sys.argv[3])
text = (gen / "generated.h").read_text()
body = text[text.index("dolrecomp_find_original(u32 address)"):]
body = body[:body.index("\n}\n")]

block = re.compile(
    r"u32 offset = address - 0x([0-9A-Fa-f]+)u;\s*"
    r"if \(offset < 0x([0-9A-Fa-f]+)u && \(offset & 3u\) == 0u\) \{\s*"
    r"static const DolRecompFunction chunk_functions\[\] = \{(.*?)\};\s*"
    r"return chunk_functions\[offset / 0x([0-9A-Fa-f]+)u\];", re.S)
single = re.compile(
    r"if \(address >= 0x([0-9A-Fa-f]+)u && address < 0x([0-9A-Fa-f]+)u && "
    r"\(\(address - 0x[0-9A-Fa-f]+u\) & 3u\) == 0u\) return (func_[0-9A-Fa-f]{8});")

entries = []   # (start, size, stride, [functions])
for m in block.finditer(body):
    fns = re.findall(r"func_[0-9A-Fa-f]{8}", m.group(3))
    entries.append((int(m.group(1), 16), int(m.group(2), 16),
                    int(m.group(4), 16), fns))
for m in single.finditer(body):
    a, b = int(m.group(1), 16), int(m.group(2), 16)
    entries.append((a, b - a, max(b - a, 4), [m.group(3)]))

expected = body.count("return chunk_functions[") + len(single.findall(body))
if len(entries) != expected or not entries:
    raise SystemExit(f"{gen}: parsed {len(entries)} of {expected} lookup entries")

entries.sort()
for (s0, z0, _, _), (s1, _, _, _) in zip(entries, entries[1:]):
    if s0 + z0 > s1:
        raise SystemExit(f"overlapping ranges at 0x{s0:08X} and 0x{s1:08X}")

fns, rows = [], []
for start, size, stride, flist in entries:
    rows.append((start, size, stride, len(fns)))
    fns.extend(flist)

with out.open("w") as f:
    f.write("// Generated by game/module/gen_native_index.py - do not edit.\n")
    f.write(f"// {len(rows)} ranges, {len(fns)} functions, from {gen}/generated.h\n")
    f.write(f"#define {prefix}_RANGES {len(rows)}u\n")
    f.write(f"static const struct {{ u32 start, size, stride, first; }} "
            f"{prefix}_range[] = {{\n")
    for r in rows:
        f.write("    {0x%08Xu, 0x%Xu, 0x%Xu, %uu},\n" % r)
    f.write("};\n")
    f.write(f"static void (*const {prefix}_fn[])(CPUState*) = {{\n")
    for name in fns:
        f.write(f"    {name},\n")
    f.write("};\n")
print(f"{out}: {len(rows)} ranges, {len(fns)} functions")
