/* Generated by tools/gen-patch-table.py - do not edit.
 *
 * Sorted by address and binary-searched: this is consulted on every
 * guest call that reaches the dispatch hook, so a linear scan over the
 * whole table would be paid continuously.
 */
#include "patch_table.h"
#include <stdlib.h>

typedef struct { uint32_t address; MgsSdkFn fn; } MgsPatch;

static const MgsPatch k_patches[] = {
    {0x800050B4u, mgs_memset},   /* memset */
    {0x800050E4u, mgs___fill_mem},   /* __fill_mem */
    {0x8000519Cu, mgs_memcpy},   /* memcpy */
    {0x8001B5FCu, mgs_PPCMfmsr},   /* PPCMfmsr */
    {0x8001B604u, mgs_PPCMtmsr},   /* PPCMtmsr */
    {0x8001B60Cu, mgs_PPCMfhid0},   /* PPCMfhid0 */
    {0x8001B614u, mgs_PPCMthid0},   /* PPCMthid0 */
    {0x8001B63Cu, mgs_PPCHalt},   /* PPCHalt */
    {0x8001B6C8u, mgs_PPCMfhid2},   /* PPCMfhid2 */
    {0x8001B6D0u, mgs_PPCMthid2},   /* PPCMthid2 */
    {0x8001B6ECu, mgs_PPCDisableSpeculation},   /* PPCDisableSpeculation */
    {0x8001B714u, mgs_PPCSetFpNonIEEEMode},   /* PPCSetFpNonIEEEMode */
    {0x8001CDC4u, mgs___OSInitAudioSystem},   /* __OSInitAudioSystem */
    {0x8001CF80u, mgs___OSStopAudioSystem},   /* __OSStopAudioSystem */
    {0x8001D058u, mgs_DCEnable},   /* DCEnable */
    {0x8001D06Cu, mgs_DCInvalidateRange},   /* DCInvalidateRange */
    {0x8001D098u, mgs_DCFlushRange},   /* DCFlushRange */
    {0x8001D0C8u, mgs_DCStoreRange},   /* DCStoreRange */
    {0x8001D0F8u, mgs_DCFlushRangeNoSync},   /* DCFlushRangeNoSync */
    {0x8001D150u, mgs_ICInvalidateRange},   /* ICInvalidateRange */
    {0x8001D184u, mgs_ICFlashInvalidate},   /* ICFlashInvalidate */
    {0x8001D194u, mgs_ICEnable},   /* ICEnable */
    {0x8001D2ACu, mgs_LCDisable},   /* LCDisable */
    {0x8001D3B8u, mgs_L2GlobalInvalidate},   /* L2GlobalInvalidate */
    {0x8001DF44u, mgs_OSReport},   /* OSReport */
    {0x8001FCCCu, mgs_OSDisableInterrupts},   /* OSDisableInterrupts */
    {0x8001FCE0u, mgs_OSEnableInterrupts},   /* OSEnableInterrupts */
    {0x8001FCF4u, mgs_OSRestoreInterrupts},   /* OSRestoreInterrupts */
    {0x800240D8u, mgs_OSGetTime},   /* OSGetTime */
    {0x800240F0u, mgs_OSGetTick},   /* OSGetTick */
    {0x80026970u, mgs_DVDConvertPathToEntrynum},   /* DVDConvertPathToEntrynum */
    {0x80026C64u, mgs_DVDFastOpen},   /* DVDFastOpen */
    {0x80026CD8u, mgs_DVDOpen},   /* DVDOpen */
    {0x80026DA0u, mgs_DVDClose},   /* DVDClose */
    {0x80026FE8u, mgs_DVDReadAsyncPrio},   /* DVDReadAsyncPrio */
    {0x80028E00u, mgs_DVDReadAbsAsyncPrio},   /* DVDReadAbsAsyncPrio */
    {0x80029360u, mgs_DVDGetCommandBlockStatus},   /* DVDGetCommandBlockStatus */
    {0x80029804u, mgs_DVDGetCurrentDiskID},   /* DVDGetCurrentDiskID */
    {0x80029DE8u, mgs_DVDCompareDiskID},   /* DVDCompareDiskID */
};

#define MGS_PATCH_COUNT 39u

/* MGS_UNPATCH=<addr>[,<addr>...]: run the TRANSLATED code
 * for these instead of our shim.
 *
 * A shim is a claim that the real code cannot run here yet,
 * and such a claim goes stale: __OSInitAudioSystem was
 * stubbed because 'the flags it waits for will never be
 * raised however carefully the registers are modelled', and
 * a later test drove that whole sequence against the model
 * with every wait passing. Withdrawing a shim to check
 * should not need a rebuild, or it will not be done. */
static int unpatched(uint32_t address)
{
    static const char* list;
    static int looked;
    const char* p;
    if (!looked) { looked = 1; list = getenv("MGS_UNPATCH"); }
    if (!list) return 0;
    for (p = list; *p; ) {
        char* end = 0;
        unsigned long v = strtoul(p, &end, 0);
        if (end == p) break;
        if ((uint32_t)v == address) return 1;
        p = (*end == ',') ? end + 1 : end;
    }
    return 0;
}

MgsSdkFn mgs_patch_lookup(uint32_t address)
{
    uint32_t lo = 0u, hi = MGS_PATCH_COUNT;
    if (unpatched(address)) return 0;
    while (lo < hi) {
        uint32_t mid = lo + (hi - lo) / 2u;
        if (k_patches[mid].address == address) return k_patches[mid].fn;
        if (k_patches[mid].address < address) lo = mid + 1u;
        else hi = mid;
    }
    return 0;
}
