/* Generated by tools/gen-patch-table.py - do not edit.
 *
 * Sorted by address and binary-searched: this is consulted on every
 * guest call that reaches the dispatch hook, so a linear scan over the
 * whole table would be paid continuously.
 */
#include "patch_table.h"
#include <stdlib.h>

typedef struct { uint32_t address; MgsSdkFn fn; } MgsPatch;

static const MgsPatch k_patches[] = {
    {0x800050B4u, mgs_memset},   /* memset */
    {0x800050E4u, mgs___fill_mem},   /* __fill_mem */
    {0x8000519Cu, mgs_memcpy},   /* memcpy */
    {0x8001B5FCu, mgs_PPCMfmsr},   /* PPCMfmsr */
    {0x8001B604u, mgs_PPCMtmsr},   /* PPCMtmsr */
    {0x8001B60Cu, mgs_PPCMfhid0},   /* PPCMfhid0 */
    {0x8001B614u, mgs_PPCMthid0},   /* PPCMthid0 */
    {0x8001B63Cu, mgs_PPCHalt},   /* PPCHalt */
    {0x8001B6C8u, mgs_PPCMfhid2},   /* PPCMfhid2 */
    {0x8001B6D0u, mgs_PPCMthid2},   /* PPCMthid2 */
    {0x8001B6ECu, mgs_PPCDisableSpeculation},   /* PPCDisableSpeculation */
    {0x8001B714u, mgs_PPCSetFpNonIEEEMode},   /* PPCSetFpNonIEEEMode */
    {0x8001CDC4u, mgs___OSInitAudioSystem},   /* __OSInitAudioSystem */
    {0x8001CF80u, mgs___OSStopAudioSystem},   /* __OSStopAudioSystem */
    {0x8001D058u, mgs_DCEnable},   /* DCEnable */
    {0x8001D06Cu, mgs_DCInvalidateRange},   /* DCInvalidateRange */
    {0x8001D098u, mgs_DCFlushRange},   /* DCFlushRange */
    {0x8001D0C8u, mgs_DCStoreRange},   /* DCStoreRange */
    {0x8001D0F8u, mgs_DCFlushRangeNoSync},   /* DCFlushRangeNoSync */
    {0x8001D150u, mgs_ICInvalidateRange},   /* ICInvalidateRange */
    {0x8001D184u, mgs_ICFlashInvalidate},   /* ICFlashInvalidate */
    {0x8001D194u, mgs_ICEnable},   /* ICEnable */
    {0x8001D2ACu, mgs_LCDisable},   /* LCDisable */
    {0x8001D3B8u, mgs_L2GlobalInvalidate},   /* L2GlobalInvalidate */
    {0x8001DF44u, mgs_OSReport},   /* OSReport */
    {0x8001FCCCu, mgs_OSDisableInterrupts},   /* OSDisableInterrupts */
    {0x8001FCE0u, mgs_OSEnableInterrupts},   /* OSEnableInterrupts */
    {0x8001FCF4u, mgs_OSRestoreInterrupts},   /* OSRestoreInterrupts */
    {0x800240D8u, mgs_OSGetTime},   /* OSGetTime */
    {0x800240F0u, mgs_OSGetTick},   /* OSGetTick */
    {0x80026970u, mgs_DVDConvertPathToEntrynum},   /* DVDConvertPathToEntrynum */
    {0x80026C64u, mgs_DVDFastOpen},   /* DVDFastOpen */
    {0x80026CD8u, mgs_DVDOpen},   /* DVDOpen */
    {0x80026DA0u, mgs_DVDClose},   /* DVDClose */
    {0x80026FE8u, mgs_DVDReadAsyncPrio},   /* DVDReadAsyncPrio */
    {0x80028E00u, mgs_DVDReadAbsAsyncPrio},   /* DVDReadAbsAsyncPrio */
    {0x80029360u, mgs_DVDGetCommandBlockStatus},   /* DVDGetCommandBlockStatus */
    {0x80029804u, mgs_DVDGetCurrentDiskID},   /* DVDGetCurrentDiskID */
    {0x80029DE8u, mgs_DVDCompareDiskID},   /* DVDCompareDiskID */
};

#define MGS_PATCH_COUNT 39u

/* MGS_UNPATCH=<addr>[,<addr>...]: run the TRANSLATED code
 * for these instead of our shim.
 *
 * A shim is a claim that the real code cannot run here yet,
 * and such a claim goes stale: __OSInitAudioSystem was
 * stubbed because 'the flags it waits for will never be
 * raised however carefully the registers are modelled', and
 * a later test drove that whole sequence against the model
 * with every wait passing. Withdrawing a shim to check
 * should not need a rebuild, or it will not be done. */
static int unpatched(uint32_t address)
{
    static const char* list;
    static int looked;
    const char* p;
    if (!looked) { looked = 1; list = getenv("MGS_UNPATCH"); }
    if (!list) return 0;
    for (p = list; *p; ) {
        char* end = 0;
        unsigned long v = strtoul(p, &end, 0);
        if (end == p) break;
        if ((uint32_t)v == address) return 1;
        p = (*end == ',') ? end + 1 : end;
    }
    return 0;
}

/* A HASH, NOT A SEARCH, BECAUSE OF HOW OFTEN THIS IS ASKED.
 *
 * Thirty-nine entries make a binary search look free - six iterations. It
 * is not free, because it runs on every guest call to a patched address and
 * the game calls two of them incessantly: `OSDisableInterrupts` and
 * `OSRestoreInterrupts` are 55.8 MILLION calls each in one run, the SDK's
 * critical section around everything. A host profile puts this function at
 * the top of the whole program, 3.95%, ahead of the rasteriser.
 *
 * Six data-dependent branches per lookup, a hundred and eleven million
 * times, none of them predictable. Open addressing over 256 slots makes it
 * one load and one compare: the table holds 39 entries, so it is 15% full
 * and probes almost never collide. Guest addresses are four-byte aligned,
 * so the index takes the bits above that.
 *
 * Address zero is not a valid patch target - these are all 0x800xxxxx - so
 * it doubles as the empty marker. */
#define PATCH_SLOT_BITS 8u
#define PATCH_SLOTS (1u << PATCH_SLOT_BITS)
#define PATCH_MASK (PATCH_SLOTS - 1u)

static uint32_t  s_slot_addr[PATCH_SLOTS];
static MgsSdkFn  s_slot_fn[PATCH_SLOTS];
static int       s_slots_built;

static void build_slots(void)
{
    uint32_t i;
    for (i = 0u; i < MGS_PATCH_COUNT; ++i) {
        uint32_t h = (k_patches[i].address >> 2) & PATCH_MASK;
        while (s_slot_addr[h]) h = (h + 1u) & PATCH_MASK;
        s_slot_addr[h] = k_patches[i].address;
        s_slot_fn[h] = k_patches[i].fn;
    }
    s_slots_built = 1;
}

MgsSdkFn mgs_patch_lookup(uint32_t address)
{
    uint32_t h = (address >> 2) & PATCH_MASK;

    if (!s_slots_built) build_slots();
    for (;;) {
        uint32_t a = s_slot_addr[h];
        if (a == address) {
            /* Checked only on a HIT. A miss returns nothing either way, and
             * this walks a string when MGS_UNPATCH is set. */
            return unpatched(address) ? 0 : s_slot_fn[h];
        }
        if (!a) return 0;
        h = (h + 1u) & PATCH_MASK;
    }
}
