/* Generated by tools/gen-patch-table.py - do not edit.
 *
 * Sorted by address and binary-searched: this is consulted on every
 * guest call that reaches the dispatch hook, so a linear scan over the
 * whole table would be paid continuously.
 */
#include "patch_table.h"

typedef struct { uint32_t address; MgsSdkFn fn; } MgsPatch;

static const MgsPatch k_patches[] = {
    {0x8001DF44u, mgs_OSReport},   /* OSReport */
    {0x8001FCCCu, mgs_OSDisableInterrupts},   /* OSDisableInterrupts */
    {0x8001FCE0u, mgs_OSEnableInterrupts},   /* OSEnableInterrupts */
    {0x8001FCF4u, mgs_OSRestoreInterrupts},   /* OSRestoreInterrupts */
    {0x800240D8u, mgs_OSGetTime},   /* OSGetTime */
    {0x800240F0u, mgs_OSGetTick},   /* OSGetTick */
    {0x80026970u, mgs_DVDConvertPathToEntrynum},   /* DVDConvertPathToEntrynum */
    {0x80026C64u, mgs_DVDFastOpen},   /* DVDFastOpen */
    {0x80026CD8u, mgs_DVDOpen},   /* DVDOpen */
    {0x80026DA0u, mgs_DVDClose},   /* DVDClose */
    {0x80026FE8u, mgs_DVDReadAsyncPrio},   /* DVDReadAsyncPrio */
    {0x80029360u, mgs_DVDGetCommandBlockStatus},   /* DVDGetCommandBlockStatus */
};

#define MGS_PATCH_COUNT 12u

MgsSdkFn mgs_patch_lookup(uint32_t address)
{
    uint32_t lo = 0u, hi = MGS_PATCH_COUNT;
    while (lo < hi) {
        uint32_t mid = lo + (hi - lo) / 2u;
        if (k_patches[mid].address == address) return k_patches[mid].fn;
        if (k_patches[mid].address < address) lo = mid + 1u;
        else hi = mid;
    }
    return 0;
}
