/* Generated by tools/gen-patch-table.py - do not edit. */
#ifndef MGS_PATCH_TABLE_H
#define MGS_PATCH_TABLE_H

#include <stdint.h>

typedef struct CPUState CPUState;
typedef void (*MgsSdkFn)(CPUState* ctx);

/* Returns the native implementation for a guest address, or NULL. */
MgsSdkFn mgs_patch_lookup(uint32_t address);

void mgs_OSReport(CPUState* ctx);
void mgs_OSDisableInterrupts(CPUState* ctx);
void mgs_OSEnableInterrupts(CPUState* ctx);
void mgs_OSRestoreInterrupts(CPUState* ctx);
void mgs_OSGetTime(CPUState* ctx);
void mgs_OSGetTick(CPUState* ctx);

#endif
