/* Generated by tools/gen-patch-table.py - do not edit. */
#ifndef MGS_PATCH_TABLE_H
#define MGS_PATCH_TABLE_H

#include <stdint.h>

typedef struct CPUState CPUState;
typedef void (*MgsSdkFn)(CPUState* ctx);

/* Returns the native implementation for a guest address, or NULL. */
MgsSdkFn mgs_patch_lookup(uint32_t address);

void mgs_PPCMfmsr(CPUState* ctx);
void mgs_PPCMtmsr(CPUState* ctx);
void mgs_PPCMfhid0(CPUState* ctx);
void mgs_PPCMthid0(CPUState* ctx);
void mgs_PPCHalt(CPUState* ctx);
void mgs_PPCMfhid2(CPUState* ctx);
void mgs_PPCMthid2(CPUState* ctx);
void mgs_PPCDisableSpeculation(CPUState* ctx);
void mgs_PPCSetFpNonIEEEMode(CPUState* ctx);
void mgs_DCEnable(CPUState* ctx);
void mgs_DCInvalidateRange(CPUState* ctx);
void mgs_DCFlushRange(CPUState* ctx);
void mgs_DCStoreRange(CPUState* ctx);
void mgs_DCFlushRangeNoSync(CPUState* ctx);
void mgs_ICInvalidateRange(CPUState* ctx);
void mgs_ICFlashInvalidate(CPUState* ctx);
void mgs_ICEnable(CPUState* ctx);
void mgs_LCDisable(CPUState* ctx);
void mgs_L2GlobalInvalidate(CPUState* ctx);
void mgs_OSReport(CPUState* ctx);
void mgs_OSDisableInterrupts(CPUState* ctx);
void mgs_OSEnableInterrupts(CPUState* ctx);
void mgs_OSRestoreInterrupts(CPUState* ctx);
void mgs_OSGetTime(CPUState* ctx);
void mgs_OSGetTick(CPUState* ctx);
void mgs_DVDConvertPathToEntrynum(CPUState* ctx);
void mgs_DVDFastOpen(CPUState* ctx);
void mgs_DVDOpen(CPUState* ctx);
void mgs_DVDClose(CPUState* ctx);
void mgs_DVDReadAsyncPrio(CPUState* ctx);
void mgs_DVDGetCommandBlockStatus(CPUState* ctx);
void mgs_DVDGetCurrentDiskID(CPUState* ctx);
void mgs_DVDCompareDiskID(CPUState* ctx);

#endif
