#!/usr/bin/env python3
"""Generate the SDK patch table from config/symbols/.

This is the design document's central mechanism: for each SDK function the
game calls, the runtime provides a NATIVE implementation and the translated
original is never executed. The boundary between translated and native is the
SDK's public API - documented, stable across GameCube titles, and for this
game entirely inside main.dol (see HANDOFF F9).

DolRecomp already ships the hook. With DOLRECOMP_ENABLE_REPLACEMENTS defined,
dolrecomp_call consults dolrecomp_dispatch_replacement BEFORE its own table,
so returning 1 from there means "handled natively, do not run the translated
code". Phase 1's cross-module router proved that path works.

Emits a sorted address table plus a binary-search lookup. Sorted and searched
rather than switch()ed because this sits in the hot dispatch path and a linear
scan over ~400 entries would be paid on every guest call.
"""
import re, argparse, sys

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--symbols', required=True)
    ap.add_argument('--implemented', required=True,
                    help='file listing SDK function names the runtime implements, one per line')
    ap.add_argument('--out-c', required=True)
    ap.add_argument('--out-h', required=True)
    a = ap.parse_args()

    named = {}
    for line in open(a.symbols):
        m = re.match(r'^(\.\w+) 0x([0-9A-Fa-f]+) \S+ (\S+) (\S+)', line)
        if m and m.group(1) == '.text':
            named.setdefault(m.group(3), int(m.group(2), 16))

    want, missing = [], []
    for line in open(a.implemented):
        name = line.split('#')[0].strip()
        if not name:
            continue
        if name in named:
            want.append((named[name], name))
        else:
            missing.append(name)

    want.sort()

    with open(a.out_h, 'w') as f:
        f.write("/* Generated by tools/gen-patch-table.py - do not edit. */\n"
                "#ifndef MGS_PATCH_TABLE_H\n#define MGS_PATCH_TABLE_H\n\n"
                "#include <stdint.h>\n\n"
                "typedef struct CPUState CPUState;\n"
                "typedef void (*MgsSdkFn)(CPUState* ctx);\n\n"
                "/* Returns the native implementation for a guest address, or NULL. */\n"
                "MgsSdkFn mgs_patch_lookup(uint32_t address);\n\n")
        for _, name in want:
            f.write(f"void mgs_{name}(CPUState* ctx);\n")
        f.write("\n#endif\n")

    with open(a.out_c, 'w') as f:
        f.write("/* Generated by tools/gen-patch-table.py - do not edit.\n"
                " *\n"
                " * Sorted by address and binary-searched: this is consulted on every\n"
                " * guest call that reaches the dispatch hook, so a linear scan over the\n"
                " * whole table would be paid continuously.\n"
                " */\n"
                '#include "patch_table.h"\n\n'
                "typedef struct { uint32_t address; MgsSdkFn fn; } MgsPatch;\n\n"
                "static const MgsPatch k_patches[] = {\n")
        for addr, name in want:
            f.write(f"    {{0x{addr:08X}u, mgs_{name}}},   /* {name} */\n")
        if not want:
            f.write("    {0u, 0},  /* C rejects a zero-sized array */\n")
        f.write("};\n\n")
        f.write(f"#define MGS_PATCH_COUNT {len(want)}u\n\n"
                "MgsSdkFn mgs_patch_lookup(uint32_t address)\n{\n"
                "    uint32_t lo = 0u, hi = MGS_PATCH_COUNT;\n"
                "    while (lo < hi) {\n"
                "        uint32_t mid = lo + (hi - lo) / 2u;\n"
                "        if (k_patches[mid].address == address) return k_patches[mid].fn;\n"
                "        if (k_patches[mid].address < address) lo = mid + 1u;\n"
                "        else hi = mid;\n"
                "    }\n"
                "    return 0;\n}\n")

    print(f"patch table: {len(want)} SDK functions patched")
    if missing:
        print(f"  NOT IN THE SYMBOL MAP ({len(missing)}), so not patchable yet:")
        for n in missing[:12]:
            print(f"    {n}")
        if len(missing) > 12:
            print(f"    ... and {len(missing)-12} more")
    return 0

if __name__ == '__main__':
    sys.exit(main())
